version: '3.4'

services:
  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  indimin.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

